# Generated by Django 2.2.5 on 2019-09-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_new', models.CharField(help_text='title of news', max_length=300)),
                ('data_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
